### ISSUE TITLE
Support Constantinople fork

### ISSUE THREAD

**Issue by disconnect3d** [trailofbits/manticore#1349]
The constantinople fork is going to be there very soon:
https://blog.ethereum.org/2019/01/11/ethereum-constantinople-upgrade-announcement/

This issue is meant to track the progress of things that needs to be done to support the new fork:

* [ ] #1166 - EIP 145: Bitwise shifting instructions in EVM
* [ ] #1165 - EIP 1014: Skinny CREATE2
* [ ] #1164 - EIP 1052: EXTCODEHASH opcode
* [ ] #1348 - EIP 1283: Net gas metering for SSTORE without dirty maps
* [ ] EIP 1234: Constantinople Difficulty Bomb Delay and Block Reward Adjustment - **to be checked if it requires Manticore changes**

The Constantinople fork implementation should be done in a class that inherits from `EVM` like `EVM_Constantinople`. Note that this requires some changes in Manticore to support different forks, but it should not be hard to add.

**Comment by ehennenfent** [comment]
Superseded by #1569
